### ISSUE TITLE
Missing Metadata

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/Adafruit_CircuitPython_Pypixelbuf#29]
While working on Circup, I found this library did not have __version__ and __repo_ meta data.

I don't think it is setup to autoversion as well, but not sure.
circup freeze reports the version as None... so prolly.

This is the common format.

```python
__version__ = "0.0.0-auto.0"
__repo__ = "https://github.com/adafruit/Adafruit_CircuitPython_Pypixelbuf.git"
```
Without __repo__, Circup can not install  library dependencies.

**Comment by ladyada** [comment]
oi
@askpatrickw would you mind submitting the PR and tag me? ill merge it! im surprised it went without for so long :D
